### ISSUE TITLE
Pipeline fails right away - Using OCP Manual Option

### ISSUE THREAD

**Issue by kylebassett** [siamaksade/openshift-cd-demo#69] opened 2017-12-18 05:09 UTC
Seems to fail right away...

OpenShift Build cicd/tasks-pipeline-3
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: No such DSL method 'pipeline' found among steps [archive, bat, build, catchError, checkout, container, deleteDir, dir, echo, error, fileExists, findFiles, getContext, git, input, isUnix, library, libraryResource, load, mail, node, openshiftBuild, openshiftCreateResource, openshiftDeleteResourceByJsonYaml, openshiftDeleteResourceByKey, openshiftDeleteResourceByLabels, openshiftDeploy, openshiftExec, openshiftImageStream, openshiftScale, openshiftTag, openshiftVerifyBuild, openshiftVerifyDeployment, openshiftVerifyService, parallel, podTemplate, properties, publishHTML, pwd, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, resolveScm, retry, sh, sha1, sleep, stage, stash, step, svn, timeout, tool, touch, unarchive, unstash, unzip, waitUntil, withContext, withEnv, wrap, writeFile, writeJSON, writeMavenPom, writeYaml, ws, zip] or symbols [all, always, androidLint, apiToken, architecture, archiveArtifacts, artifactManager, batchFile, booleanParam, buildButton, buildDiscarder, caseInsensitive, caseSensitive, checkstyle, choice, choiceParam, clock, cloud, command, configMapVolume, containerEnvVar, containerTemplate, cron, crumb, defaultView, demand, dependencyCheckAnalyzer, dependencyCheckPublisher, dependencyCheckUpdateOnly, dependencyTrackPublisher, disableConcurrentBuilds, downloadSettings, downstream, dumb, emptyDirVolume, emptyDirWorkspaceVolume, envVars, file, fileParam, filePath, findbugs, fingerprint, frameOptions, freeStyle, freeStyleJob, git, hostPathVolume, hostPathWorkspaceVolume, hyperlink, hyperlinkToModels, installSource, jacoco, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobName, junit, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, myView, nfsVolume, nfsWorkspaceVolume, nodeProperties, nonStoredPasswordParam, none, overrideIndexTriggers, paneStatus, parameters, password, pattern, persistentVolumeClaim, persistentVolumeClaimWorkspaceVolume, pipelineTriggers, plainText, plugin, pmd, podAnnotation, podEnvVar, pollSCM, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, remotingCLI, run, runParam, schedule, scmRetryCount, search, secretVolume, security, shell, slave, stackTrace, standard, status, string, stringParam, swapSpace, text, textParam, tmpSpace, toolLocation, unsecured, upstream, viewsTabBar, weather, zfs, zip] or globals [currentBuild, env, fileLoader, params, scm]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:149)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:103)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:74)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:165)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by kylebassett** [comment] 2017-12-18 05:29
thinking it may be related to this:
oc import-image jenkins --from="registry.access.redhat.com/openshift3/jenkins-2-rhel7" --confirm --all -n openshift

info: The remote repository contained 25 additional tags which were not imported: v3.3, v3.2, v3.1, 2.32, 2.32-15, 2.32-13, 2.32-8, 2.32-7, 2.32-4, 2.19, 2.19-15, 2.19-13, 2.7, 2.7-7, v3.7.9, v3.7.9-21, v3.6.173.0.21, v3.6.173.0.21-17, v3.6.173.0.49, v3.6.173.0.49-5, v3.6.173.0.5, v3.6.173.0.5-2, v3.6.173.0.5-5, v3.6.173.0.83, v3.6.173.0.83-2

**Comment by kylebassett** [comment] 2017-12-18 05:57
https://stackoverflow.com/questions/47048960/jenkinsfile-error-java-lang-nosuchmethoderror-no-such-dsl-method-withmaven-f

**Comment by jclingan-demo** [comment] 2017-12-27 07:07
@kylearctiq The problem is that the Jenkins image that is being downloaded is not using a new enough version of Jenkins pipeline plugin. Go into the Jenkins image setting, manage plugins, and update the pipeline plugin, which will also update plugin dependencies. Once I did this and restarted jenkins (well, and updated other pipeline-related plugins at the same time), it worked just fine.

So, me-thinks either a newer version of the Jenkins image needs to be created or somewhere in the bazillion lines of the yaml setup, a newer version of the Jenkins image needs to be used if it exists.

**Comment by Ronnie-Wang** [comment] 2018-01-30 07:03
I have the same problems on this steps.

I have updated all the plugins which is related with pipeline. And then re-run oc start-build tasks-pipeline in command line. It threw new problems.

Attach the console output.
OpenShift Build cicd/tasks-pipeline-3
[Pipeline] node
Still waiting to schedule task
maven-41f67da21fa1c3 is offline
Running on maven-41f67da21fa1c3 in /tmp/workspace/cicd-tasks-pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build App)
[Pipeline] git
Cloning the remote Git repository
Cloning repository http://gogs:3000/gogs/openshift-tasks.git
 > git init /tmp/workspace/cicd-tasks-pipeline # timeout=10
Fetching upstream changes from http://gogs:3000/gogs/openshift-tasks.git
 > git --version # timeout=10
 > git fetch --tags --progress http://gogs:3000/gogs/openshift-tasks.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress http://gogs:3000/gogs/openshift-tasks.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: repository 'http://gogs:3000/gogs/openshift-tasks.git/' not found

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to JNLP4-connect connection from cloudvlan1.bcsdc.lexington.ibm.com/10.128.0.1:50894(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy90.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1067)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test)
Stage 'Test' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Code Analysis)
Stage 'Code Analysis' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Archive App)
Stage 'Archive App' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Create Image Builder)
Stage 'Create Image Builder' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Image)
Stage 'Build Image' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Create DEV)
Stage 'Create DEV' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy DEV)
Stage 'Deploy DEV' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to STAGE?)
Stage 'Promote to STAGE?' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy STAGE)
Stage 'Deploy STAGE' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: null
Finished: FAILURE

And my nexus had not been deployed successfully.
The nexus log is:
--> Scaling nexus-1 to 1
error: update acceptor rejected nexus-1: pods for rc 'cicd/nexus-1' took longer than 600 seconds to become available

![jenkins error](https://user-images.githubusercontent.com/32251699/35552304-5aad72ae-05ce-11e8-91eb-a112b7eae881.png)
![nexus error](https://user-images.githubusercontent.com/32251699/35552327-6f6836d4-05ce-11e8-9fc5-75686b4f7141.png)

Thanks.

**Comment by nobusue** [comment] 2018-02-09 07:37
I had same issue, and resolved by this workaround.

```
oc login -u system:admin
oc project openshift
oc tag jenkins:v3.7 jenkins:latest
```

When you creating pipeline build definition, OpenShift creates Jenkins pod using "jenkins:latest" image stream. So you can specify latest Jenkins image you imported before.

**Comment by Ronnie-Wang** [comment] 2018-02-09 07:44
@nobusue Thanks, nobusue, I will try it.

**Comment by sidd-harth** [comment] 2018-02-11 06:41
Thanks, @nobusue , this workaround worked for me.

**Comment by siamaksade** [comment] 2018-02-20 15:07
This is due to a temporary issue in the way jenkins images are tagged in the Red Hat registry. Added instructions to README

**Closed as completed by siamaksade** 2018-02-20 15:07 UTC

**Comment by kalkusa** [comment] 2019-12-06 16:40
I also encounter this issue. But what's interesting - only on one branch.
I deleted a file and recreated it. It works.
